---
# configure, make, make install

- stat: path="{{python_prefix}}/bin/python{{python_bin_ver}}"
  register: stat_python_bin

- name: install build depends
  dnf: name={{item}} state=present
  with_items:
    # build
    - gcc
    - make
    # deps
    - zlib-devel
    - bzip2-devel
    - openssl-devel
    - ncurses-devel
    - sqlite-devel
    - readline-devel
    - gdbm-devel
    - db4-devel
    - libpcap-devel
    - xz-devel
    - tk-devel
    - tcl-devel
    - expat-devel
    # deps: Pillow
    - libjpeg-turbo-devel
  become: yes
  when: not stat_python_bin.stat.exists

- name: clear old src dir
  file: >-
    path="{{python_src_dir}}"
    state=absent
  become: yes
  when: not stat_python_bin.stat.exists

- name: create work dir
  file: >-
    path="{{work_dir}}/python"
    state=directory mode=0777
  become: yes
  when: not stat_python_bin.stat.exists

- name: download src
  get_url: >-
    url="{{python_src_url}}"
    dest="{{python_src}}"
    sha256sum="{{python_src_hash}}"
  when: not stat_python_bin.stat.exists

- name: unarchive
  unarchive: >-
    src="{{python_src}}"
    dest="{{work_dir}}/python"
  when: not stat_python_bin.stat.exists

- name: configure
  command: "{{python_configure}} chdir={{python_src_dir}}"
  when: not stat_python_bin.stat.exists

- name: make
  command: >-
    make
    chdir="{{python_src_dir}}"
  when: not stat_python_bin.stat.exists

- name: mkdir install path
  file: >-
    path="{{python_prefix}}"
    state=directory
  become: yes
  when: not stat_python_bin.stat.exists

- name: make install
  command: >-
    make install
    chdir="{{python_src_dir}}"
  become: yes
  when: not stat_python_bin.stat.exists

# vim:st=2 sts=2 sw=2:
