---
# vim: ft=yaml st=2 sts=2 sw=2 tw=0:

# add jupyter.service on systemd

- template:
    src: systemd_jupyter.service
    dest: /etc/systemd/system/jupyter.service
    owner: root
    group: root
    mode: 0644

- command: systemctl daemon-reload

- service:
    name: jupyter.service
    state: started
    enabled: yes
